/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DIS"
      | "Distribute"
      | "MAN"
      | "Manufacturing"
      | "MaterialTransactions"
      | "Materials"
      | "Owner"
      | "ProductMaterials"
      | "ProductStock"
      | "ProductTimestamps"
      | "RET"
      | "RMS"
      | "RMSsupply"
      | "Retail"
      | "VendorStats"
      | "addDistributor"
      | "addManufacturer"
      | "addMaterial"
      | "addMedicine"
      | "addProduct"
      | "addRMS"
      | "addRMSLegacy"
      | "addRetailer"
      | "disCtr"
      | "getMaterialTransactionCount"
      | "getMaterialsForProduct"
      | "getProductTimestamps"
      | "getVendorDetails"
      | "manCtr"
      | "materialCtr"
      | "productCtr"
      | "rateVendor"
      | "retCtr"
      | "rmsCtr"
      | "showStage"
      | "sold"
      | "transactionCtr"
      | "useMaterialForProduct"
      | "verifyVendor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaterialAdded"
      | "MaterialTransactionRecorded"
      | "ProductAdded"
      | "RoleAdded"
      | "StageUpdated"
      | "VendorRated"
      | "VendorVerified"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DIS", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Distribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "MAN", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "Manufacturing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MaterialTransactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "Materials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "Owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ProductMaterials",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ProductStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ProductTimestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "RET", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "RMS", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "RMSsupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "Retail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "VendorStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addMaterial",
    values: [string, string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addMedicine",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProduct",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addRMS",
    values: [AddressLike, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRMSLegacy",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addRetailer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "disCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMaterialTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaterialsForProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductTimestamps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVendorDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "manCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "materialCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateVendor",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "retCtr", values?: undefined): string;
  encodeFunctionData(functionFragment: "rmsCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sold", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transactionCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "useMaterialForProduct",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyVendor",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "DIS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Distribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "Manufacturing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MaterialTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Materials", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ProductMaterials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProductStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ProductTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RMS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RMSsupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Retail", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VendorStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMedicine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addRMS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRMSLegacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMaterialTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaterialsForProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVendorDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "materialCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "productCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateVendor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "retCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rmsCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useMaterialForProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyVendor",
    data: BytesLike
  ): Result;
}

export namespace MaterialAddedEvent {
  export type InputTuple = [
    materialId: BigNumberish,
    name: string,
    supplierId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: bigint,
    name: string,
    supplierId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: bigint;
    name: string;
    supplierId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialTransactionRecordedEvent {
  export type InputTuple = [
    txId: BigNumberish,
    materialId: BigNumberish,
    vendorId: BigNumberish,
    txType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: bigint,
    materialId: bigint,
    vendorId: bigint,
    txType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: bigint;
    materialId: bigint;
    vendorId: bigint;
    txType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductAddedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    name: string,
    quantity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    name: string,
    quantity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    name: string;
    quantity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAddedEvent {
  export type InputTuple = [
    roleType: string,
    roleId: BigNumberish,
    addr: AddressLike,
    name: string
  ];
  export type OutputTuple = [
    roleType: string,
    roleId: bigint,
    addr: string,
    name: string
  ];
  export interface OutputObject {
    roleType: string;
    roleId: bigint;
    addr: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageUpdatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    stage: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    stage: bigint,
    actor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    stage: bigint;
    actor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorRatedEvent {
  export type InputTuple = [
    vendorId: BigNumberish,
    rating: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    vendorId: bigint,
    rating: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    vendorId: bigint;
    rating: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorVerifiedEvent {
  export type InputTuple = [vendorId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [vendorId: bigint, timestamp: bigint];
  export interface OutputObject {
    vendorId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DIS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Distribute: TypedContractMethod<
    [_productID: BigNumberish],
    [void],
    "nonpayable"
  >;

  MAN: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  Manufacturing: TypedContractMethod<
    [_productID: BigNumberish],
    [void],
    "nonpayable"
  >;

  MaterialTransactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        materialId: bigint;
        vendorId: bigint;
        productId: bigint;
        quantity: bigint;
        timestamp: bigint;
        transactionType: string;
      }
    ],
    "view"
  >;

  Materials: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        category: string;
        quantity: bigint;
        unit: string;
        pricePerUnit: bigint;
        supplierId: bigint;
        addedTimestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  Owner: TypedContractMethod<[], [string], "view">;

  ProductMaterials: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  ProductStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        quantity: bigint;
        RMSid: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;

  ProductTimestamps: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        orderedTimestamp: bigint;
        rmsTimestamp: bigint;
        manufacturingTimestamp: bigint;
        distributionTimestamp: bigint;
        retailTimestamp: bigint;
        soldTimestamp: bigint;
      }
    ],
    "view"
  >;

  RET: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;

  RMS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  RMSsupply: TypedContractMethod<
    [_productID: BigNumberish],
    [void],
    "nonpayable"
  >;

  Retail: TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;

  VendorStats: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalOrders: bigint;
        completedOrders: bigint;
        totalQuantitySupplied: bigint;
        lastActivityTimestamp: bigint;
        rating: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  addDistributor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addMaterial: TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish,
      _supplierId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addMedicine: TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;

  addProduct: TypedContractMethod<
    [_name: string, _description: string, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  addRMS: TypedContractMethod<
    [
      _address: AddressLike,
      _name: string,
      _place: string,
      _contactInfo: string,
      _materialTypes: string
    ],
    [void],
    "nonpayable"
  >;

  addRMSLegacy: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addRetailer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  disCtr: TypedContractMethod<[], [bigint], "view">;

  getMaterialTransactionCount: TypedContractMethod<[], [bigint], "view">;

  getMaterialsForProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getProductTimestamps: TypedContractMethod<
    [_productID: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        ordered: bigint;
        rms: bigint;
        manufacturing: bigint;
        distribution: bigint;
        retail: bigint;
        sold_time: bigint;
      }
    ],
    "view"
  >;

  getVendorDetails: TypedContractMethod<
    [_vendorId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        place: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
        totalOrders: bigint;
        completedOrders: bigint;
        totalQuantitySupplied: bigint;
        rating: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  manCtr: TypedContractMethod<[], [bigint], "view">;

  materialCtr: TypedContractMethod<[], [bigint], "view">;

  productCtr: TypedContractMethod<[], [bigint], "view">;

  rateVendor: TypedContractMethod<
    [_vendorId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  retCtr: TypedContractMethod<[], [bigint], "view">;

  rmsCtr: TypedContractMethod<[], [bigint], "view">;

  showStage: TypedContractMethod<[_productID: BigNumberish], [string], "view">;

  sold: TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;

  transactionCtr: TypedContractMethod<[], [bigint], "view">;

  useMaterialForProduct: TypedContractMethod<
    [
      _materialId: BigNumberish,
      _productId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifyVendor: TypedContractMethod<
    [_vendorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DIS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Distribute"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "MAN"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Manufacturing"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "MaterialTransactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        materialId: bigint;
        vendorId: bigint;
        productId: bigint;
        quantity: bigint;
        timestamp: bigint;
        transactionType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Materials"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        category: string;
        quantity: bigint;
        unit: string;
        pricePerUnit: bigint;
        supplierId: bigint;
        addedTimestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "Owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ProductMaterials"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ProductStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        quantity: bigint;
        RMSid: bigint;
        MANid: bigint;
        DISid: bigint;
        RETid: bigint;
        stage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ProductTimestamps"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        orderedTimestamp: bigint;
        rmsTimestamp: bigint;
        manufacturingTimestamp: bigint;
        distributionTimestamp: bigint;
        retailTimestamp: bigint;
        soldTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RET"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RMS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "RMSsupply"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Retail"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "VendorStats"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalOrders: bigint;
        completedOrders: bigint;
        totalQuantitySupplied: bigint;
        lastActivityTimestamp: bigint;
        rating: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMaterial"
  ): TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish,
      _supplierId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMedicine"
  ): TypedContractMethod<
    [_name: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [_name: string, _description: string, _quantity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRMS"
  ): TypedContractMethod<
    [
      _address: AddressLike,
      _name: string,
      _place: string,
      _contactInfo: string,
      _materialTypes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRMSLegacy"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRetailer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaterialTransactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaterialsForProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProductTimestamps"
  ): TypedContractMethod<
    [_productID: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        ordered: bigint;
        rms: bigint;
        manufacturing: bigint;
        distribution: bigint;
        retail: bigint;
        sold_time: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVendorDetails"
  ): TypedContractMethod<
    [_vendorId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        place: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
        totalOrders: bigint;
        completedOrders: bigint;
        totalQuantitySupplied: bigint;
        rating: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "manCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "materialCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rateVendor"
  ): TypedContractMethod<
    [_vendorId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rmsCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_productID: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sold"
  ): TypedContractMethod<[_productID: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transactionCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "useMaterialForProduct"
  ): TypedContractMethod<
    [
      _materialId: BigNumberish,
      _productId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyVendor"
  ): TypedContractMethod<[_vendorId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MaterialAdded"
  ): TypedContractEvent<
    MaterialAddedEvent.InputTuple,
    MaterialAddedEvent.OutputTuple,
    MaterialAddedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialTransactionRecorded"
  ): TypedContractEvent<
    MaterialTransactionRecordedEvent.InputTuple,
    MaterialTransactionRecordedEvent.OutputTuple,
    MaterialTransactionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ProductAdded"
  ): TypedContractEvent<
    ProductAddedEvent.InputTuple,
    ProductAddedEvent.OutputTuple,
    ProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdded"
  ): TypedContractEvent<
    RoleAddedEvent.InputTuple,
    RoleAddedEvent.OutputTuple,
    RoleAddedEvent.OutputObject
  >;
  getEvent(
    key: "StageUpdated"
  ): TypedContractEvent<
    StageUpdatedEvent.InputTuple,
    StageUpdatedEvent.OutputTuple,
    StageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VendorRated"
  ): TypedContractEvent<
    VendorRatedEvent.InputTuple,
    VendorRatedEvent.OutputTuple,
    VendorRatedEvent.OutputObject
  >;
  getEvent(
    key: "VendorVerified"
  ): TypedContractEvent<
    VendorVerifiedEvent.InputTuple,
    VendorVerifiedEvent.OutputTuple,
    VendorVerifiedEvent.OutputObject
  >;

  filters: {
    "MaterialAdded(uint256,string,uint256,uint256)": TypedContractEvent<
      MaterialAddedEvent.InputTuple,
      MaterialAddedEvent.OutputTuple,
      MaterialAddedEvent.OutputObject
    >;
    MaterialAdded: TypedContractEvent<
      MaterialAddedEvent.InputTuple,
      MaterialAddedEvent.OutputTuple,
      MaterialAddedEvent.OutputObject
    >;

    "MaterialTransactionRecorded(uint256,uint256,uint256,string,uint256)": TypedContractEvent<
      MaterialTransactionRecordedEvent.InputTuple,
      MaterialTransactionRecordedEvent.OutputTuple,
      MaterialTransactionRecordedEvent.OutputObject
    >;
    MaterialTransactionRecorded: TypedContractEvent<
      MaterialTransactionRecordedEvent.InputTuple,
      MaterialTransactionRecordedEvent.OutputTuple,
      MaterialTransactionRecordedEvent.OutputObject
    >;

    "ProductAdded(uint256,string,uint256,uint256)": TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;
    ProductAdded: TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;

    "RoleAdded(string,uint256,address,string)": TypedContractEvent<
      RoleAddedEvent.InputTuple,
      RoleAddedEvent.OutputTuple,
      RoleAddedEvent.OutputObject
    >;
    RoleAdded: TypedContractEvent<
      RoleAddedEvent.InputTuple,
      RoleAddedEvent.OutputTuple,
      RoleAddedEvent.OutputObject
    >;

    "StageUpdated(uint256,uint8,address,uint256)": TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;
    StageUpdated: TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;

    "VendorRated(uint256,uint256,uint256)": TypedContractEvent<
      VendorRatedEvent.InputTuple,
      VendorRatedEvent.OutputTuple,
      VendorRatedEvent.OutputObject
    >;
    VendorRated: TypedContractEvent<
      VendorRatedEvent.InputTuple,
      VendorRatedEvent.OutputTuple,
      VendorRatedEvent.OutputObject
    >;

    "VendorVerified(uint256,uint256)": TypedContractEvent<
      VendorVerifiedEvent.InputTuple,
      VendorVerifiedEvent.OutputTuple,
      VendorVerifiedEvent.OutputObject
    >;
    VendorVerified: TypedContractEvent<
      VendorVerifiedEvent.InputTuple,
      VendorVerifiedEvent.OutputTuple,
      VendorVerifiedEvent.OutputObject
    >;
  };
}
