/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChain {
  export type MaterialStruct = {
    id: BigNumberish;
    name: string;
    category: string;
    totalQuantity: BigNumberish;
    availableQuantity: BigNumberish;
    unit: string;
    pricePerUnit: BigNumberish;
    vendorId: BigNumberish;
    receivedAt: BigNumberish;
    isActive: boolean;
  };

  export type MaterialStructOutput = [
    id: bigint,
    name: string,
    category: string,
    totalQuantity: bigint,
    availableQuantity: bigint,
    unit: string,
    pricePerUnit: bigint,
    vendorId: bigint,
    receivedAt: bigint,
    isActive: boolean
  ] & {
    id: bigint;
    name: string;
    category: string;
    totalQuantity: bigint;
    availableQuantity: bigint;
    unit: string;
    pricePerUnit: bigint;
    vendorId: bigint;
    receivedAt: bigint;
    isActive: boolean;
  };

  export type ProductStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    targetQuantity: BigNumberish;
    manufacturerId: BigNumberish;
    distributorId: BigNumberish;
    retailerId: BigNumberish;
    stage: BigNumberish;
    createdAt: BigNumberish;
  };

  export type ProductStructOutput = [
    id: bigint,
    name: string,
    description: string,
    targetQuantity: bigint,
    manufacturerId: bigint,
    distributorId: bigint,
    retailerId: bigint,
    stage: bigint,
    createdAt: bigint
  ] & {
    id: bigint;
    name: string;
    description: string;
    targetQuantity: bigint;
    manufacturerId: bigint;
    distributorId: bigint;
    retailerId: bigint;
    stage: bigint;
    createdAt: bigint;
  };

  export type ProductMaterialUsageStruct = {
    materialId: BigNumberish;
    quantityUsed: BigNumberish;
    assignedAt: BigNumberish;
  };

  export type ProductMaterialUsageStructOutput = [
    materialId: bigint,
    quantityUsed: bigint,
    assignedAt: bigint
  ] & { materialId: bigint; quantityUsed: bigint; assignedAt: bigint };

  export type ProductTimelineStruct = {
    createdAt: BigNumberish;
    materialsAssignedAt: BigNumberish;
    manufacturingStartedAt: BigNumberish;
    manufacturingCompletedAt: BigNumberish;
    distributionStartedAt: BigNumberish;
    retailReceivedAt: BigNumberish;
    soldAt: BigNumberish;
  };

  export type ProductTimelineStructOutput = [
    createdAt: bigint,
    materialsAssignedAt: bigint,
    manufacturingStartedAt: bigint,
    manufacturingCompletedAt: bigint,
    distributionStartedAt: bigint,
    retailReceivedAt: bigint,
    soldAt: bigint
  ] & {
    createdAt: bigint;
    materialsAssignedAt: bigint;
    manufacturingStartedAt: bigint;
    manufacturingCompletedAt: bigint;
    distributionStartedAt: bigint;
    retailReceivedAt: bigint;
    soldAt: bigint;
  };

  export type VendorStruct = {
    id: BigNumberish;
    addr: AddressLike;
    name: string;
    location: string;
    contactInfo: string;
    materialTypes: string;
    registeredAt: BigNumberish;
    isActive: boolean;
  };

  export type VendorStructOutput = [
    id: bigint,
    addr: string,
    name: string,
    location: string,
    contactInfo: string,
    materialTypes: string,
    registeredAt: bigint,
    isActive: boolean
  ] & {
    id: bigint;
    addr: string;
    name: string;
    location: string;
    contactInfo: string;
    materialTypes: string;
    registeredAt: bigint;
    isActive: boolean;
  };
}

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Owner"
      | "addDistributor"
      | "addManufacturer"
      | "addMaterial"
      | "addRetailer"
      | "addVendor"
      | "assignMaterialToProduct"
      | "confirmAndStartManufacturing"
      | "createProduct"
      | "distributorCtr"
      | "distributors"
      | "findDistributor"
      | "findManufacturer"
      | "findRetailer"
      | "findVendor"
      | "getMaterial"
      | "getProduct"
      | "getProductMaterials"
      | "getProductMaterialsCount"
      | "getProductTimeline"
      | "getVendor"
      | "manufacturerCtr"
      | "manufacturerSelectMaterial"
      | "manufacturers"
      | "markAsSold"
      | "materialCtr"
      | "materials"
      | "productCtr"
      | "productMaterials"
      | "productTimelines"
      | "products"
      | "receiveAtRetail"
      | "restockMaterial"
      | "retailerCtr"
      | "retailers"
      | "showStage"
      | "startDistribution"
      | "startManufacturing"
      | "supplyHistory"
      | "supplyHistoryCtr"
      | "vendorAddMaterial"
      | "vendorCtr"
      | "vendorRestockMaterial"
      | "vendors"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributorAdded"
      | "ManufacturerAdded"
      | "MaterialAdded"
      | "MaterialRestocked"
      | "MaterialsAssignedToProduct"
      | "ProductCreated"
      | "RetailerAdded"
      | "StageUpdated"
      | "VendorAdded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "Owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addMaterial",
    values: [string, string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addRetailer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addVendor",
    values: [AddressLike, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "assignMaterialToProduct",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmAndStartManufacturing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProduct",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "findDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findRetailer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "findVendor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaterial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductMaterials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductMaterialsCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductTimeline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVendor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturerCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturerSelectMaterial",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "manufacturers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "materialCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "materials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productMaterials",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productTimelines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAtRetail",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "restockMaterial",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retailerCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retailers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startManufacturing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyHistoryCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vendorAddMaterial",
    values: [string, string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vendorCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vendorRestockMaterial",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vendors",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "Owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addVendor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignMaterialToProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmAndStartManufacturing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findRetailer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "findVendor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductMaterials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductMaterialsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductTimeline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVendor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manufacturerCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manufacturerSelectMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manufacturers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsSold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "materialCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "materials", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "productCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productMaterials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productTimelines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveAtRetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restockMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retailerCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "retailers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startManufacturing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyHistoryCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vendorAddMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vendorCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vendorRestockMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vendors", data: BytesLike): Result;
}

export namespace DistributorAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, name: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManufacturerAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, name: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialAddedEvent {
  export type InputTuple = [
    materialId: BigNumberish,
    name: string,
    vendorId: BigNumberish,
    quantity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: bigint,
    name: string,
    vendorId: bigint,
    quantity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: bigint;
    name: string;
    vendorId: bigint;
    quantity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialRestockedEvent {
  export type InputTuple = [
    materialId: BigNumberish,
    quantity: BigNumberish,
    vendorId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: bigint,
    quantity: bigint,
    vendorId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: bigint;
    quantity: bigint;
    vendorId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialsAssignedToProductEvent {
  export type InputTuple = [
    productId: BigNumberish,
    materialId: BigNumberish,
    quantity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    materialId: bigint,
    quantity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    materialId: bigint;
    quantity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductCreatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    name: string,
    targetQuantity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    name: string,
    targetQuantity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    name: string;
    targetQuantity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetailerAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [id: bigint, name: string, timestamp: bigint];
  export interface OutputObject {
    id: bigint;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StageUpdatedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    stage: BigNumberish,
    actor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    stage: bigint,
    actor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    stage: bigint;
    actor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VendorAddedEvent {
  export type InputTuple = [
    vendorId: BigNumberish,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [vendorId: bigint, name: string, timestamp: bigint];
  export interface OutputObject {
    vendorId: bigint;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Owner: TypedContractMethod<[], [string], "view">;

  addDistributor: TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;

  addMaterial: TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish,
      _vendorId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addRetailer: TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;

  addVendor: TypedContractMethod<
    [
      _addr: AddressLike,
      _name: string,
      _location: string,
      _contactInfo: string,
      _materialTypes: string
    ],
    [void],
    "nonpayable"
  >;

  assignMaterialToProduct: TypedContractMethod<
    [
      _productId: BigNumberish,
      _materialId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  confirmAndStartManufacturing: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProduct: TypedContractMethod<
    [_name: string, _description: string, _targetQuantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributorCtr: TypedContractMethod<[], [bigint], "view">;

  distributors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  findDistributor: TypedContractMethod<[_addr: AddressLike], [bigint], "view">;

  findManufacturer: TypedContractMethod<[_addr: AddressLike], [bigint], "view">;

  findRetailer: TypedContractMethod<[_addr: AddressLike], [bigint], "view">;

  findVendor: TypedContractMethod<[_addr: AddressLike], [bigint], "view">;

  getMaterial: TypedContractMethod<
    [_materialId: BigNumberish],
    [SupplyChain.MaterialStructOutput],
    "view"
  >;

  getProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductStructOutput],
    "view"
  >;

  getProductMaterials: TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductMaterialUsageStructOutput[]],
    "view"
  >;

  getProductMaterialsCount: TypedContractMethod<
    [_productId: BigNumberish],
    [bigint],
    "view"
  >;

  getProductTimeline: TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductTimelineStructOutput],
    "view"
  >;

  getVendor: TypedContractMethod<
    [_vendorId: BigNumberish],
    [SupplyChain.VendorStructOutput],
    "view"
  >;

  manufacturerCtr: TypedContractMethod<[], [bigint], "view">;

  manufacturerSelectMaterial: TypedContractMethod<
    [
      _productId: BigNumberish,
      _materialId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  manufacturers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  markAsSold: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  materialCtr: TypedContractMethod<[], [bigint], "view">;

  materials: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        category: string;
        totalQuantity: bigint;
        availableQuantity: bigint;
        unit: string;
        pricePerUnit: bigint;
        vendorId: bigint;
        receivedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  productCtr: TypedContractMethod<[], [bigint], "view">;

  productMaterials: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        materialId: bigint;
        quantityUsed: bigint;
        assignedAt: bigint;
      }
    ],
    "view"
  >;

  productTimelines: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        createdAt: bigint;
        materialsAssignedAt: bigint;
        manufacturingStartedAt: bigint;
        manufacturingCompletedAt: bigint;
        distributionStartedAt: bigint;
        retailReceivedAt: bigint;
        soldAt: bigint;
      }
    ],
    "view"
  >;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        targetQuantity: bigint;
        manufacturerId: bigint;
        distributorId: bigint;
        retailerId: bigint;
        stage: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  receiveAtRetail: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  restockMaterial: TypedContractMethod<
    [
      _materialId: BigNumberish,
      _quantity: BigNumberish,
      _vendorId: BigNumberish,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  retailerCtr: TypedContractMethod<[], [bigint], "view">;

  retailers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  showStage: TypedContractMethod<[_productId: BigNumberish], [string], "view">;

  startDistribution: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  startManufacturing: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supplyHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        materialId: bigint;
        vendorId: bigint;
        quantity: bigint;
        pricePerUnit: bigint;
        totalAmount: bigint;
        suppliedAt: bigint;
      }
    ],
    "view"
  >;

  supplyHistoryCtr: TypedContractMethod<[], [bigint], "view">;

  vendorAddMaterial: TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  vendorCtr: TypedContractMethod<[], [bigint], "view">;

  vendorRestockMaterial: TypedContractMethod<
    [
      _materialId: BigNumberish,
      _quantity: BigNumberish,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  vendors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMaterial"
  ): TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish,
      _vendorId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRetailer"
  ): TypedContractMethod<
    [_addr: AddressLike, _name: string, _location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addVendor"
  ): TypedContractMethod<
    [
      _addr: AddressLike,
      _name: string,
      _location: string,
      _contactInfo: string,
      _materialTypes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignMaterialToProduct"
  ): TypedContractMethod<
    [
      _productId: BigNumberish,
      _materialId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmAndStartManufacturing"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<
    [_name: string, _description: string, _targetQuantity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributorCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findDistributor"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "findManufacturer"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "findRetailer"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "findVendor"
  ): TypedContractMethod<[_addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaterial"
  ): TypedContractMethod<
    [_materialId: BigNumberish],
    [SupplyChain.MaterialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductMaterials"
  ): TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductMaterialUsageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductMaterialsCount"
  ): TypedContractMethod<[_productId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProductTimeline"
  ): TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ProductTimelineStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVendor"
  ): TypedContractMethod<
    [_vendorId: BigNumberish],
    [SupplyChain.VendorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "manufacturerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manufacturerSelectMaterial"
  ): TypedContractMethod<
    [
      _productId: BigNumberish,
      _materialId: BigNumberish,
      _quantity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manufacturers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsSold"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "materialCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "materials"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        category: string;
        totalQuantity: bigint;
        availableQuantity: bigint;
        unit: string;
        pricePerUnit: bigint;
        vendorId: bigint;
        receivedAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "productCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productMaterials"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        materialId: bigint;
        quantityUsed: bigint;
        assignedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "productTimelines"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        createdAt: bigint;
        materialsAssignedAt: bigint;
        manufacturingStartedAt: bigint;
        manufacturingCompletedAt: bigint;
        distributionStartedAt: bigint;
        retailReceivedAt: bigint;
        soldAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        name: string;
        description: string;
        targetQuantity: bigint;
        manufacturerId: bigint;
        distributorId: bigint;
        retailerId: bigint;
        stage: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveAtRetail"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restockMaterial"
  ): TypedContractMethod<
    [
      _materialId: BigNumberish,
      _quantity: BigNumberish,
      _vendorId: BigNumberish,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retailerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "retailers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "startDistribution"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startManufacturing"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supplyHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        materialId: bigint;
        vendorId: bigint;
        quantity: bigint;
        pricePerUnit: bigint;
        totalAmount: bigint;
        suppliedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supplyHistoryCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vendorAddMaterial"
  ): TypedContractMethod<
    [
      _name: string,
      _category: string,
      _quantity: BigNumberish,
      _unit: string,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vendorCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vendorRestockMaterial"
  ): TypedContractMethod<
    [
      _materialId: BigNumberish,
      _quantity: BigNumberish,
      _pricePerUnit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vendors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        addr: string;
        name: string;
        location: string;
        contactInfo: string;
        materialTypes: string;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DistributorAdded"
  ): TypedContractEvent<
    DistributorAddedEvent.InputTuple,
    DistributorAddedEvent.OutputTuple,
    DistributorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ManufacturerAdded"
  ): TypedContractEvent<
    ManufacturerAddedEvent.InputTuple,
    ManufacturerAddedEvent.OutputTuple,
    ManufacturerAddedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialAdded"
  ): TypedContractEvent<
    MaterialAddedEvent.InputTuple,
    MaterialAddedEvent.OutputTuple,
    MaterialAddedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialRestocked"
  ): TypedContractEvent<
    MaterialRestockedEvent.InputTuple,
    MaterialRestockedEvent.OutputTuple,
    MaterialRestockedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialsAssignedToProduct"
  ): TypedContractEvent<
    MaterialsAssignedToProductEvent.InputTuple,
    MaterialsAssignedToProductEvent.OutputTuple,
    MaterialsAssignedToProductEvent.OutputObject
  >;
  getEvent(
    key: "ProductCreated"
  ): TypedContractEvent<
    ProductCreatedEvent.InputTuple,
    ProductCreatedEvent.OutputTuple,
    ProductCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RetailerAdded"
  ): TypedContractEvent<
    RetailerAddedEvent.InputTuple,
    RetailerAddedEvent.OutputTuple,
    RetailerAddedEvent.OutputObject
  >;
  getEvent(
    key: "StageUpdated"
  ): TypedContractEvent<
    StageUpdatedEvent.InputTuple,
    StageUpdatedEvent.OutputTuple,
    StageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VendorAdded"
  ): TypedContractEvent<
    VendorAddedEvent.InputTuple,
    VendorAddedEvent.OutputTuple,
    VendorAddedEvent.OutputObject
  >;

  filters: {
    "DistributorAdded(uint256,string,uint256)": TypedContractEvent<
      DistributorAddedEvent.InputTuple,
      DistributorAddedEvent.OutputTuple,
      DistributorAddedEvent.OutputObject
    >;
    DistributorAdded: TypedContractEvent<
      DistributorAddedEvent.InputTuple,
      DistributorAddedEvent.OutputTuple,
      DistributorAddedEvent.OutputObject
    >;

    "ManufacturerAdded(uint256,string,uint256)": TypedContractEvent<
      ManufacturerAddedEvent.InputTuple,
      ManufacturerAddedEvent.OutputTuple,
      ManufacturerAddedEvent.OutputObject
    >;
    ManufacturerAdded: TypedContractEvent<
      ManufacturerAddedEvent.InputTuple,
      ManufacturerAddedEvent.OutputTuple,
      ManufacturerAddedEvent.OutputObject
    >;

    "MaterialAdded(uint256,string,uint256,uint256,uint256)": TypedContractEvent<
      MaterialAddedEvent.InputTuple,
      MaterialAddedEvent.OutputTuple,
      MaterialAddedEvent.OutputObject
    >;
    MaterialAdded: TypedContractEvent<
      MaterialAddedEvent.InputTuple,
      MaterialAddedEvent.OutputTuple,
      MaterialAddedEvent.OutputObject
    >;

    "MaterialRestocked(uint256,uint256,uint256,uint256)": TypedContractEvent<
      MaterialRestockedEvent.InputTuple,
      MaterialRestockedEvent.OutputTuple,
      MaterialRestockedEvent.OutputObject
    >;
    MaterialRestocked: TypedContractEvent<
      MaterialRestockedEvent.InputTuple,
      MaterialRestockedEvent.OutputTuple,
      MaterialRestockedEvent.OutputObject
    >;

    "MaterialsAssignedToProduct(uint256,uint256,uint256,uint256)": TypedContractEvent<
      MaterialsAssignedToProductEvent.InputTuple,
      MaterialsAssignedToProductEvent.OutputTuple,
      MaterialsAssignedToProductEvent.OutputObject
    >;
    MaterialsAssignedToProduct: TypedContractEvent<
      MaterialsAssignedToProductEvent.InputTuple,
      MaterialsAssignedToProductEvent.OutputTuple,
      MaterialsAssignedToProductEvent.OutputObject
    >;

    "ProductCreated(uint256,string,uint256,uint256)": TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;
    ProductCreated: TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;

    "RetailerAdded(uint256,string,uint256)": TypedContractEvent<
      RetailerAddedEvent.InputTuple,
      RetailerAddedEvent.OutputTuple,
      RetailerAddedEvent.OutputObject
    >;
    RetailerAdded: TypedContractEvent<
      RetailerAddedEvent.InputTuple,
      RetailerAddedEvent.OutputTuple,
      RetailerAddedEvent.OutputObject
    >;

    "StageUpdated(uint256,uint8,address,uint256)": TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;
    StageUpdated: TypedContractEvent<
      StageUpdatedEvent.InputTuple,
      StageUpdatedEvent.OutputTuple,
      StageUpdatedEvent.OutputObject
    >;

    "VendorAdded(uint256,string,uint256)": TypedContractEvent<
      VendorAddedEvent.InputTuple,
      VendorAddedEvent.OutputTuple,
      VendorAddedEvent.OutputObject
    >;
    VendorAdded: TypedContractEvent<
      VendorAddedEvent.InputTuple,
      VendorAddedEvent.OutputTuple,
      VendorAddedEvent.OutputObject
    >;
  };
}
